### PR TITLE
Fix deprecation issues

### LINKED ISSUE #30: Make this package compatible with latest Atom version
apm is complaining that there is no compatible version of this package for 1.0.19. Could you please make it compatible? Or at least provide a compatibility matrix on the readme.

Regards

### PR DESCRIPTION
**Pull request by TobiasBales**
[closes #30, 29, 28, 27, 26, 24, 23, 22, 21, 20, 19]

### CODE REVIEW

**Comment by laughedelic** [comment]
Is it published?

```
 » apm-beta show github-issues                                                                                                                                        [off] 00:30:37
github-issues
├── 0.5.0
├── https://github.com/baconscript/github-issues
├── GitHub issue tracking from within Atom.
├── 990 downloads
└── 6 stars

Run `apm install github-issues` to install this package.

 » apm-beta install github-issues                                                                                                                                     [off] 00:30:37
Installing github-issues to /Users/laughedelic/.atom/packages ✗
No available version compatible with the installed Atom version: 1.6.0
```

**Comment by r24y** [comment]
Whoops! Working on it.

**Comment by r24y** [comment]
I made a mistake with the versions, but it's all good. `github-issues@0.7.0` is published.

**Comment by laughedelic** [comment]
ok. I've installed it. check #32, please

**Pull request merged**
